#
# Makefile for mach
#

obj-$(CONFIG_ARCH_MMP)				+= mmpx-dt.o power_domain_gc.o pxa1928_lowpower.o pm.o pm-pxa1928.o pxa1908-dt.o fuseinfo-pxa1928.o pxa1928_smc_lowlevel.o pxa1928_smc.o
obj-$(CONFIG_UIO_HANTRO)			+= power_domain_hantro.o
obj-$(CONFIG_UIO_CODA7542)			+= power_domain_coda7542.o
obj-$(CONFIG_ARM_SMMU)				+= power_domain_smmu.o
obj-$(CONFIG_VIDEO_MMPISP_B52)			+= power_domain_isp.o
obj-$(CONFIG_VIDEO_MV_SC2_MMU)			+= power_domain_sc2.o
obj-$(CONFIG_CORESIGHT_SUPPORT)			+= coresight-v8.o
