ccflags-y += -Idrivers/marvell/marvell-telephony-v2/include \
			 -Idrivers/marvell/marvell-telephony-v2/pcac/shmem/inc \
			 -Idrivers/marvell/marvell-telephony-v2/pcac/ci_data/inc

TARGET := ccinetdev
#obj-m  += ccinet.o
$(TARGET)-objs := ccinet.o
obj-m	:= $(TARGET).o

